FROM php:7.3-apache

### DEFINE PASTA DOCUMENT_ROOT ###
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

### INSTALA COMPOSER ###
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

### INSTALA EXTENSOES E MODULOS NECESSARIOS ###
RUN a2enmod rewrite
RUN docker-php-ext-install pdo_mysql

### INSTALA XDEBUG ###
RUN pecl install xdebug

### RODA COMPOSER INSTALL ###
# RUN composer install --prefer-dist